adam_epsilon: 1.0e-08
beam_size: 10
clean_up_tokenization_spaces: true
data_dir: /home/gurnoor/PADA/data
data_procesor_obj: !!python/name:src.data_processing.absa.pada.AbsaSeq2SeqPadaDataProcessor ''
dataset_obj: !!python/name:src.data_processing.absa.pada.AbsaSeq2SeqPadaDataset ''
dataset_specific_kwargs: !!python/object:argparse.Namespace
  mixture_alpha: 0.2
  proportion_aspect: 0.3333
diversity_penalty: 0.2
eval_batch_size: 24
eval_metrics:
- binary_f1
- micro_f1
- macro_f1
- weighted_f1
experiment_dir: /home/gurnoor/PADA/runs
gradient_accumulation_steps: 1
learning_rate: 5.0e-05
length_penalty: 1.0
max_seq_len: 128
mixture_alpha: 0.2
multi_diversity_penalty: 0.2
n_gpu: 1
num_beam_groups: 5
num_return_sequences: 4
num_train_epochs: 60
output_dir: /home/gurnoor/PADA/runs/absa/rest/PADA/e60/b24/a0.2
proportion_aspect: 0.3333
repetition_penalty: 2.0
skip_special_tokens: true
src_domains:
- device
- laptops
- service
t5_model_name: t5-base
train_batch_size: 24
trg_domain: rest
warmup_steps: 0
weight_decay: 1.0e-05
